- name: Digital IT Acquisition Professional (DITAP) Training
  description: |
    Become a certified digial acquisition professional through our
    expert-led, 6-month, part-time course.
  url: /work/services/training/ditap/
- name: Digital IT Acquisition Professional (DITAP) Training — Executive Edition
  description: |
    Learn how to lead your agency into the world of modern procurement
    through a condensed, 1-day version of our 6-month DITAP program.
  url: /work/services/training/ditap-executive/